### ISSUE TITLE
What is the meaning of common and consensus?

### ISSUE THREAD

**Issue by Orz-CQ** [marschall-lab/pangenome-growth#1]
Hi,

Thanks for this approach to check the GFA file's growth plot.
But I am curious the meaning of "common" and "consensus".
Which means the number that all accessions contained? I guess "common".
What about "consensus"?

Best wishes,
Lan

**Comment by danydoerr** [comment]
Hi Lan,

admittedly, these labels have been chosen somewhat arbitrarily. "Common" means that the corresponding node/base pair/edge appears in *all* accessions, whereas consensus counts those appearing in >=50%. 

We are working on an entirely revised version that will be released soon where these labels can be set by the user. 

-dany

**Comment by Orz-CQ** [comment]
Hi dany,

Thanks for your soon reply.

I have one more question.
Here, in the plot, `least-squares fit to m*X^ (m=20331763.197, γ=0.811)`.
What can we get from this number? 
Such as what the meaning of the higher m or higher γ?

Many thanks!
Lan

**Comment by Orz-CQ** [comment]
Got it.
Thanks!
